// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClips(arg1, arg2) {
  return window['go']['main']['App']['GetClips'](arg1, arg2);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PasteClip(arg1) {
  return window['go']['main']['App']['PasteClip'](arg1);
}

export function SearchClips(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchClips'](arg1, arg2, arg3);
}
