// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetClips(arg1:number,arg2:number):Promise<Array<domain.ClipItem>>;

export function HideWindow():Promise<void>;

export function PasteClip(arg1:string):Promise<void>;

export function SearchClips(arg1:string,arg2:number,arg3:number):Promise<Array<domain.ClipItem>>;

export function ShowWindow():Promise<void>;
