name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ".go-version"
          cache-dependency-path: "go.sum"

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build macOS App
        run: |
          wails build -platform darwin/universal -clean

      - name: Create DMG
        working-directory: build/bin
        run: |
          npx create-dmg --overwrite --no-code-sign kura.app

      - name: Upload Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} build/bin/*.dmg --generate-notes